Arran10126/08
XccelerateOrg/FTWD_Web_Day_02 pull request #22
Opened 2020-08-26 05:14 UTC by arran101

finished exercise D, wanted to do exercise E but need to move on to the next days work because i'm still playing catchup

2020-08-26 05:17 UTC, arran101 commented
also idk why, its called this pull request Arran10126/08, when the commit comment is called exercises up to e done. Can you explain why thats happened?

2020-08-31 06:38 UTC, samoshaughnessy commented on Exercise_C/index.css
> +    background-color: blue;
Hey Arran, this code works well, but conventionally it could be better:

height/ width properties are repeated throughout classes

2020-08-31 06:39 UTC, samoshaughnessy commented on Exercise_D and E/assets/style/index.css
> +    background-image: url("/code/FTWD_Web_Day_02/Exercise_D and E/assets/images/flowershop.jpg");
This looks like its the wrong path? it could be shorter? 
"../images/flowershop.jpg"

2020-08-31 06:40 UTC, samoshaughnessy requested changes
Please deal with the changes within the pull request

2020-08-31 10:15 UTC, lezzles11 reviewed
Good work for completing everything - keep it up! :)

2020-08-31 10:15 UTC, lezzles11 commented on README.md
> +Got to play around a lot more with flex boxes, which deffo helped. The froggy game was a really good way to practice them.
Great that you updated this!

2021-01-11 01:26 UTC, closed without merging